name: Backend Services CI
# targeting pull requests to master branch
on:
  workflow_call:
jobs:
  Backend_build:
    name: Backend build
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ${{matrix.os}}
    concurrency:
      group: build-test
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        service: [assignment-service, grading-service, user-service]

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Clean up
        run: |
          rm -rf backend/${{matrix.service}}/node_modules
          rm -rf backend/${{matrix.service}}/coverage

      - name: Install Dependencies Using yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: backend/${{matrix.service}}

      - name: Run Yarn Build
        env:
          NODE_ENV: test
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: backend/${{matrix.service}}
  Backend_tests:
    name: Backend tests
    needs: Backend_build
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ${{matrix.os}}
    concurrency:
      group: build-test
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        service: [assignment-service, grading-service, user-service]

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Clean up
        run: |
          rm -rf backend/${{matrix.service}}/node_modules
          rm -rf backend/${{matrix.service}}/coverage

      - name: Install Dependencies Using yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: backend/${{matrix.service}}
