name: Frontend CI
on:
  workflow_call:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  frontend_build:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Clean up
        run: |
          rm -rf frontend/node_modules
          rm -rf frontend/coverage
      - name: Install Dependencies Using yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: frontend
      - name: Run Next Build
        env:
          NODE_ENV: test
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: frontend
  
  frontend_tests:
    name: Frontend Tests
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Clean up
        run: |
          rm -rf frontend/node_modules
          rm -rf frontend/coverage
      - name: Install Dependencies Using yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: frontend

      - name: Run Test Suites
        env:
          NODE_ENV: test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: frontend
  